version: '3'

services:
  rails:
    container_name: rails
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/rails:delegated
    ports:
      - 3000:3000
