name: Run rspec

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0.0

      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Bundler and gem install
        run: |
          cd rails
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      # - name: Yarn install
      #   run: |
      #     yarn install --check-files

      - name: Database create and migrate
        run: |
          cd rails
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run rspec
        run: |
          cd rails
          bundle exec rspec
